services:
  rails_app:
    image: rental_building:development
    container_name: rental_building_rails_app_development
    restart: unless-stopped
    volumes:
      - rails_app:/app/tmp
    networks:
      - rental_building_backend
    ports:
      - "8000:3000"
    env_file:
      - .development.env

  db:
    image: postgres:11-alpine
    container_name: rental_building_database_development
    networks:
      - rental_building_backend
    restart: unless-stopped
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - .development.env

volumes:
  rails_app:
  postgresql-data:
  redis:

networks:
  rental_building_backend:
    driver: bridge
